apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  keycloak.url: {{ .Values.config.keycloakUrl | quote }}
  keycloak.realm: {{ .Values.config.keycloakRealm | quote }}
  command.service.url: {{ .Values.config.commandServiceUrl | quote }}
  query.service.url: {{ .Values.config.queryServiceUrl | quote }}
  rate.limit.requests.per.minute: {{ .Values.config.rateLimitRequestsPerMinute | quote }}
  cors.allowed.origins: {{ .Values.config.corsAllowedOrigins | quote }}
