apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-query-service.fullname" . }}
  labels:
    {{- include "order-query-service.labels" . | nindent 4 }}
data:
  kafka.bootstrap.servers: {{ .Values.config.kafkaBootstrapServers | quote }}
  kafka.schema.registry.url: {{ .Values.config.kafkaSchemaRegistryUrl | quote }}
  kafka.application.id: {{ .Values.config.kafkaApplicationId | quote }}
  elasticsearch.hosts: {{ .Values.config.elasticsearchHosts | quote }}
  elasticsearch.username: {{ .Values.config.elasticsearchUsername | quote }}
  elasticsearch.index.name: {{ .Values.config.elasticsearchIndexName | quote }}
