apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-query-service.fullname" . }}
  labels:
    {{- include "order-query-service.labels" . | nindent 4 }}
type: Opaque
data:
  elasticsearch-password: {{ .Values.secrets.elasticsearchPassword | b64enc | quote }}
  keycloak-client-secret: {{ .Values.secrets.keycloakClientSecret | b64enc | quote }}
