global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'order-platform-local'
    environment: 'development'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'api-gateway'

  - job_name: 'order-command-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-command-service:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'order-command-service'

  - job_name: 'order-query-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-query-service:8082']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'order-query-service'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
