apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-command-service.fullname" . }}
  labels:
    {{- include "order-command-service.labels" . | nindent 4 }}
data:
  postgres.username: {{ .Values.config.postgresUsername | quote }}
  kafka.bootstrap.servers: {{ .Values.config.kafkaBootstrapServers | quote }}
  kafka.schema.registry.url: {{ .Values.config.kafkaSchemaRegistryUrl | quote }}
  snapshot.interval: {{ .Values.config.snapshotInterval | quote }}
