apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-command-service.fullname" . }}
  labels:
    {{- include "order-command-service.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  keycloak-client-secret: {{ .Values.secrets.keycloakClientSecret | b64enc | quote }}
